# Generated by Django 2.0.6 on 2018-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_auto_20180616_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
